//! LLVM IR 文本后端
//!
//! 将 IrModule 发射为 LLVM IR 文本格式（.ll 文件）。
//! 这是 IR 到最终可编译 LLVM IR 的主要输出通道。

use super::block::IrBasicBlock;
use super::function::{IrFunction, IrLinkage};
use super::module::IrModule;
use super::types::IrType;
use super::value::{IrInstruction, IrTerminator};
use crate::error::cayResult;

/// LLVM IR 文本后端
pub struct LlvmBackend {
    /// 输出缓冲区
    output: String,
    /// 当前缩进级别
    indent: usize,
    /// 字符串常量注册表
    string_decls: Vec<String>,
}

impl LlvmBackend {
    /// 创建新的 LLVM 后端
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            string_decls: Vec::new(),
        }
    }

    /// 将 IR 模块发射为 LLVM IR 文本
    pub fn emit(&mut self, module: &IrModule) -> cayResult<String> {
        self.output.clear();
        self.string_decls.clear();

        // 模块头部
        self.emit_module_header(module);

        // 目标三元组
        self.emit_line(&format!("target triple = \"{}\"", module.target_triple));
        self.emit_line("");

        // 字符串常量声明
        self.emit_string_constants(module);

        // 类型声明
        self.emit_type_declarations(module);

        // 外部声明
        self.emit_extern_declarations(module);

        // 全局变量
        self.emit_global_variables(module);

        // 函数定义
        for func in &module.functions {
            self.emit_function(module, func)?;
        }

        Ok(self.output.clone())
    }

    // ============================================================
    // 模块头部
    // ============================================================

    fn emit_module_header(&mut self, module: &IrModule) {
        self.emit_line(&format!(
            "; Module '{}' - generated by Cavvy IR Backend",
            module.name
        ));
        self.emit_line(&format!("; Source language: Cavvy"));
        self.emit_line("");

        let stats = module.stats();
        self.emit_line(&format!(
            "; Stats: {} functions, {} blocks, {} instructions, {} strings",
            stats.function_count, stats.block_count, stats.instruction_count, stats.string_count
        ));
        self.emit_line("");
    }

    // ============================================================
    // 字符串常量
    // ============================================================

    fn emit_string_constants(&mut self, module: &IrModule) {
        if module.string_constants.is_empty() {
            return;
        }

        self.emit_line("; String constants");
        for (name, value) in &module.string_constants {
            let escaped = value
                .replace("\\", "\\5C")
                .replace("\"", "\\22")
                .replace("\n", "\\0A")
                .replace("\r", "\\0D")
                .replace("\t", "\\09")
                .replace("\0", "\\00");
            let len = value.as_bytes().len() + 1;
            self.emit_line(&format!(
                "{} = private unnamed_addr constant [{} x i8] c\"{}\\00\", align 1",
                name, len, escaped
            ));
        }
        self.emit_line("");
    }

    // ============================================================
    // 类型声明
    // ============================================================

    fn emit_type_declarations(&mut self, module: &IrModule) {
        if module.type_declarations.is_empty() {
            return;
        }

        self.emit_line("; Type declarations");
        for decl in &module.type_declarations {
            let field_strs: Vec<String> =
                decl.fields.iter().map(|(_, ty)| ty.to_llvm_str()).collect();
            self.emit_line(&format!(
                "%{} = type {{ {} }}",
                decl.name,
                field_strs.join(", ")
            ));
        }
        self.emit_line("");
    }

    // ============================================================
    // 外部声明
    // ============================================================

    fn emit_extern_declarations(&mut self, module: &IrModule) {
        if module.extern_declarations.is_empty() {
            return;
        }

        self.emit_line("; External declarations");
        for decl in &module.extern_declarations {
            let ret_str = decl.return_type.to_llvm_str();
            let param_strs: Vec<String> =
                decl.params.iter().map(|(_, ty)| ty.to_llvm_str()).collect();

            let mut param_list = param_strs.join(", ");
            if decl.is_varargs {
                if !param_list.is_empty() {
                    param_list.push_str(", ...");
                } else {
                    param_list.push_str("...");
                }
            }

            let cc_attr = match &decl.calling_convention {
                Some(cc) => format!(" {}", cc),
                None => String::new(),
            };

            self.emit_line(&format!(
                "declare {} @{}({}){}",
                ret_str, decl.name, param_list, cc_attr
            ));
        }
        self.emit_line("");
    }

    // ============================================================
    // 全局变量
    // ============================================================

    fn emit_global_variables(&mut self, module: &IrModule) {
        if module.globals.is_empty() {
            return;
        }

        self.emit_line("; Global variables");
        for global in &module.globals {
            let linkage = match global.linkage {
                super::module::IrGlobalLinkage::External => "external",
                super::module::IrGlobalLinkage::Internal => "internal",
                super::module::IrGlobalLinkage::Private => "private",
            };

            let init_str = match &global.initializer {
                Some(val) => val.to_llvm_str(),
                None => "zeroinitializer".to_string(),
            };

            let const_str = if global.is_constant {
                "constant"
            } else {
                "global"
            };

            self.emit_line(&format!(
                "{} = {} {} {} {}",
                global.name,
                linkage,
                const_str,
                global.ty.to_llvm_str(),
                init_str
            ));
        }
        self.emit_line("");
    }

    // ============================================================
    // 函数
    // ============================================================

    fn emit_function(&mut self, _module: &IrModule, func: &IrFunction) -> cayResult<()> {
        // 声明（无函数体的函数）
        if func.linkage == IrLinkage::Declare {
            let ret_str = func.return_type.to_llvm_str();
            let param_strs: Vec<String> = func
                .params
                .iter()
                .map(|p| format!("{} %{}", p.ty.to_llvm_str(), p.name))
                .collect();
            self.emit_line(&format!(
                "declare {} @{}({})",
                ret_str,
                func.name,
                param_strs.join(", ")
            ));
            self.emit_line("");
            return Ok(());
        }

        // 函数头
        let linkage = match func.linkage {
            IrLinkage::External => "",
            IrLinkage::Internal => "internal ",
            IrLinkage::Private => "private ",
            IrLinkage::Declare => unreachable!(),
        };

        let ret_str = func.return_type.to_llvm_str();
        let param_strs: Vec<String> = func
            .params
            .iter()
            .map(|p| format!("{} %{}", p.ty.to_llvm_str(), p.name))
            .collect();

        let cc_str = match &func.calling_convention {
            Some(cc) => format!(" {}", cc),
            None => String::new(),
        };

        self.emit_line(&format!(
            "define {}{} @{}({}){} {{",
            linkage,
            ret_str,
            func.name,
            param_strs.join(", "),
            cc_str
        ));
        self.indent += 1;

        // 基本块
        for (i, block) in func.blocks.iter().enumerate() {
            if i > 0 {
                self.emit_line(""); // 块之间空行
            }
            self.emit_block(block)?;
        }

        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");
        Ok(())
    }

    // ============================================================
    // 基本块
    // ============================================================

    fn emit_block(&mut self, block: &IrBasicBlock) -> cayResult<()> {
        self.emit_line(&format!("{}:", block.label));

        for inst in &block.instructions {
            self.emit_instruction(inst)?;
        }

        if let Some(term) = &block.terminator {
            self.emit_terminator(term)?;
        }

        Ok(())
    }

    // ============================================================
    // 指令发射
    // ============================================================

    fn emit_instruction(&mut self, inst: &IrInstruction) -> cayResult<()> {
        match inst {
            IrInstruction::Alloca { result, ty, align } => {
                self.emit_line(&format!(
                    "  {} = alloca {}, align {}",
                    result.to_llvm_str(),
                    ty.to_llvm_str(),
                    align
                ));
            }

            IrInstruction::Load { result, ptr, ty } => {
                self.emit_line(&format!(
                    "  {} = load {}, {}* {}",
                    result.to_llvm_str(),
                    ty.to_llvm_str(),
                    ty.to_llvm_str(),
                    ptr.to_llvm_str()
                ));
            }

            IrInstruction::Store { value, ptr, ty } => {
                self.emit_line(&format!(
                    "  store {} {}, {}* {}",
                    ty.to_llvm_str(),
                    value.to_llvm_str(),
                    ty.to_llvm_str(),
                    ptr.to_llvm_str()
                ));
            }

            IrInstruction::BinaryOp {
                result,
                op,
                left,
                right,
            } => {
                let ty = result.ir_type();
                self.emit_line(&format!(
                    "  {} = {} {} {}, {}",
                    result.to_llvm_str(),
                    op.to_llvm_str(),
                    ty.to_llvm_str(),
                    left.to_llvm_str(),
                    right.to_llvm_str()
                ));
            }

            IrInstruction::Compare {
                result,
                op,
                left,
                right,
            } => {
                let left_ty = left.ir_type();
                let is_float = left_ty.is_float();
                let cmp_str = if is_float {
                    format!("fcmp {}", op.to_llvm_str(true))
                } else {
                    format!("icmp {}", op.to_llvm_str(false))
                };

                self.emit_line(&format!(
                    "  {} = {} {} {}, {}",
                    result.to_llvm_str(),
                    cmp_str,
                    left_ty.to_llvm_str(),
                    left.to_llvm_str(),
                    right.to_llvm_str()
                ));
            }

            IrInstruction::Cast {
                result,
                kind,
                value,
                to_ty,
            } => {
                let from_ty = value.ir_type();
                self.emit_line(&format!(
                    "  {} = {} {} {} to {}",
                    result.to_llvm_str(),
                    kind.to_llvm_str(),
                    from_ty.to_llvm_str(),
                    value.to_llvm_str(),
                    to_ty.to_llvm_str()
                ));
            }

            IrInstruction::Call {
                result,
                func_name,
                args,
                return_ty,
            } => {
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| format!("{} {}", a.ir_type().to_llvm_str(), a.to_llvm_str()))
                    .collect();

                if let Some(res) = result {
                    if *return_ty == IrType::Void {
                        self.emit_line(&format!(
                            "  call void @{}({})",
                            func_name,
                            arg_strs.join(", ")
                        ));
                    } else {
                        self.emit_line(&format!(
                            "  {} = call {} @{}({})",
                            res.to_llvm_str(),
                            return_ty.to_llvm_str(),
                            func_name,
                            arg_strs.join(", ")
                        ));
                    }
                } else {
                    self.emit_line(&format!(
                        "  call void @{}({})",
                        func_name,
                        arg_strs.join(", ")
                    ));
                }
            }

            IrInstruction::GetElementPtr {
                result,
                ptr,
                indices,
                base_ty,
            } => {
                let idx_strs: Vec<String> = indices
                    .iter()
                    .map(|i| format!("{} {}", i.ir_type().to_llvm_str(), i.to_llvm_str()))
                    .collect();
                self.emit_line(&format!(
                    "  {} = getelementptr {}, {} {}, {}",
                    result.to_llvm_str(),
                    base_ty.to_llvm_str(),
                    ptr.ir_type().to_llvm_str(),
                    ptr.to_llvm_str(),
                    idx_strs.join(", ")
                ));
            }

            IrInstruction::BitCast {
                result,
                value,
                to_ty,
            } => {
                self.emit_line(&format!(
                    "  {} = bitcast {} {} to {}",
                    result.to_llvm_str(),
                    value.ir_type().to_llvm_str(),
                    value.to_llvm_str(),
                    to_ty.to_llvm_str()
                ));
            }

            IrInstruction::Phi {
                result,
                ty,
                incoming,
            } => {
                let incoming_strs: Vec<String> = incoming
                    .iter()
                    .map(|(val, label)| format!("[ {}, %{} ]", val.to_llvm_str(), label))
                    .collect();
                self.emit_line(&format!(
                    "  {} = phi {} {}",
                    result.to_llvm_str(),
                    ty.to_llvm_str(),
                    incoming_strs.join(", ")
                ));
            }

            IrInstruction::Select {
                result,
                condition,
                true_val,
                false_val,
            } => {
                let ty = true_val.ir_type();
                self.emit_line(&format!(
                    "  {} = select i1 {}, {} {}, {} {}",
                    result.to_llvm_str(),
                    condition.to_llvm_str(),
                    ty.to_llvm_str(),
                    true_val.to_llvm_str(),
                    ty.to_llvm_str(),
                    false_val.to_llvm_str()
                ));
            }

            IrInstruction::InlineIr {
                lines,
                outputs: _,
                inputs: _,
            } => {
                // 直接输出原始 IR 行
                for line in lines {
                    self.emit_line(&format!("  {}", line));
                }
            }

            IrInstruction::Comment { text } => {
                self.emit_line(&format!("  ; {}", text));
            }

            IrInstruction::SourceLocation { line, column } => {
                self.emit_line(&format!("  ; #line {}:{}", line, column));
            }

            IrInstruction::VarDecl {
                name,
                alloca_reg: _,
                ty: _,
            } => {
                // 变量声明是元数据，仅作为注释输出
                self.emit_line(&format!("  ; var: {}", name));
            }
        }

        Ok(())
    }

    // ============================================================
    // 终止指令
    // ============================================================

    fn emit_terminator(&mut self, term: &IrTerminator) -> cayResult<()> {
        match term {
            IrTerminator::Return { value } => {
                if let Some(val) = value {
                    self.emit_line(&format!(
                        "  ret {} {}",
                        val.ir_type().to_llvm_str(),
                        val.to_raw_str()
                    ));
                } else {
                    self.emit_line("  ret void");
                }
            }

            IrTerminator::Branch { target } => {
                self.emit_line(&format!("  br label %{}", target));
            }

            IrTerminator::ConditionalBranch {
                condition,
                true_target,
                false_target,
            } => {
                self.emit_line(&format!(
                    "  br i1 {}, label %{}, label %{}",
                    condition.to_llvm_str(),
                    true_target,
                    false_target
                ));
            }

            IrTerminator::Switch {
                value,
                default_target,
                cases,
                ty,
            } => {
                self.emit_line(&format!(
                    "  switch {} {}, label %{} [",
                    ty.to_llvm_str(),
                    value.to_llvm_str(),
                    default_target
                ));
                for (case_val, case_label) in cases {
                    self.emit_line(&format!(
                        "    {} {}, label %{}",
                        ty.to_llvm_str(),
                        case_val.to_llvm_str(),
                        case_label
                    ));
                }
                self.emit_line("  ]");
            }

            IrTerminator::Unreachable => {
                self.emit_line("  unreachable");
            }
        }

        Ok(())
    }

    // ============================================================
    // 辅助方法
    // ============================================================

    fn emit_line(&mut self, line: &str) {
        if !line.is_empty() {
            for _ in 0..self.indent {
                self.output.push_str("  ");
            }
        }
        self.output.push_str(line);
        self.output.push('\n');
    }

    /// 便捷方法：一次性完成模块到 LLVM IR 文本的转换
    pub fn emit_module(module: &IrModule) -> cayResult<String> {
        let mut backend = Self::new();
        backend.emit(module)
    }
}

impl Default for LlvmBackend {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::*;

    #[test]
    fn test_empty_module() {
        let module = IrModule::new("test".to_string(), "x86_64-unknown-linux-gnu".to_string());
        let result = LlvmBackend::emit_module(&module).unwrap();
        assert!(result.contains("target triple"));
        assert!(result.contains("Module 'test'"));
    }

    #[test]
    fn test_simple_function() {
        let mut module = IrModule::new("test".to_string(), "x86_64-unknown-linux-gnu".to_string());
        let mut func = IrFunction::new("test.main".to_string(), IrType::I32, Vec::new());

        // entry: ret i32 0
        let entry = func.entry_block_mut().unwrap();
        entry.set_terminator(IrTerminator::Return {
            value: Some(IrValue::IntConst(0, IrType::I32)),
        });

        module.add_function(func);
        let result = LlvmBackend::emit_module(&module).unwrap();
        assert!(result.contains("define i32 @test.main()"));
        assert!(result.contains("ret i32 0"), "Output was:\n{}", result);
    }

    #[test]
    fn test_string_constant() {
        let mut module = IrModule::new("test".to_string(), "x86_64-unknown-linux-gnu".to_string());
        let name = module.add_string("Hello, World!");
        let result = LlvmBackend::emit_module(&module).unwrap();
        assert!(result.contains(&name));
        assert!(result.contains("Hello, World!"));
    }
}
